spring:
  application:
  name: shop

  datasource:
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true


app:
  secret-key: $2a$12$TY7Cy3L0Mz./innA6OJIFuoAt37SOaZTkUOJwLUX3g1g9tNY4M5Ge
  expiration-time: 3600000